### ISSUE TITLE
how to set slow_only = True when  iter > 0

### ISSUE THREAD

**Issue by liuxialong** [cjlin1/libmf#3]
I only find

 2910         if(iter == 0)
 2911             slow_only = false;

from mf.cpp. As twin learner described, when iter > 0, slow_only must to be set True.

But I can't find this code.

Can anybody tell me where is it?

**Comment by wschin** [comment]
No. Starting from the 2nd training iteration, slow_only should be false because when slow_only is true, only first few latent coordinate could be updated.
