### ISSUE TITLE
row-oriented pair-wise logistic loss  

### ISSUE THREAD

**Issue by oldlee11** [cjlin1/libmf#31]
请问 row-oriented pair-wise logistic loss是指对于负反馈的样本  我们随机选择一个物品作为这个用户的负反馈物品吗？然后做logistics

**Comment by oldlee11** [comment]
负反馈的score 通过-c设置

**Comment by wschin** [comment]
> 请问 row-oriented pair-wise logistic loss是指对于负反馈的样本  我们随机选择一个物品作为这个用户的负反馈物品吗？然后做logistics

Yes.

**Comment by wschin** [comment]
> 负反馈的score 通过-c设置

No. The option `-c` is for one-class matrix factorization using coordinate descent method (invoked via setting `-s 12`).

**Comment by oldlee11** [comment]
谢谢您
