### ISSUE TITLE
大文件25G训练时出现  段错误 (核心已转储)  错误

### ISSUE THREAD

**Issue by oldlee11** [cjlin1/libmf#32]
在训练25G大文件时   出现     段错误 (核心已转储)  错误

**Comment by oldlee11** [comment]
我是用gdb调试发现
Thread 1 "mf-train" received signal SIGSEGV, Segmentation fault.
0x0000000000409138 in mf::(anonymous namespace)::Utility::<lambda(mf::mf_float*, mf::mf_int, std::vector<int, std::allocator<int> >&)>::operator()(mf::mf_float *, mf::mf_int, std::vector<int, std::allocator<int> > &) const (
    __closure=0x7fffffffd3e0, ptr=0x7ff8291d5040, size=40881558, omega=std::vector of length 40881558, capacity 40881558 = {...}) at mf.cpp:598

代码定位是 mf.cpp:598
            mf_float tmp = 0;
            for(mf_int j = 0; j < model.k; ++j)
                tmp += abs(ptr[i*model.k+j]);---->int溢出变为了负数  这里修改为(long)i*model.k+j
            reg += omega[i]*tmp;

**Comment by wschin** [comment]
Thanks for reporting! Your solution looks reasonable. What's your value of i, k, and j?
