### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [cjlin1/libmf#34]
Hi, thanks for this great library! Just wanted to let you know there are now [Ruby bindings](https://github.com/ankane/libmf). It works great for collaborative filtering with both explicit and implicit feedback.

**Comment by wschin** [comment]
It's awesome! Thank you!

**Comment by ankane** [comment]
Thanks @wschin, I also just released a higher-level collaborative filtering library for it: https://github.com/ankane/disco
