### ISSUE TITLE
LIBMF++ / RPCS

### ISSUE THREAD

**Issue by ankane** [cjlin1/libmf#38]
Hi @cjlin1, I recently came across your paper on [LIBMF++](https://www.csie.ntu.edu.tw/~cjlin/papers/libmf/mf_adaptive_pakdd.pdf). It sounds like RPCS has significant performance benefits. Are there any plans to bring it to LIBMF?

**Comment by wschin** [comment]
It's in LIBMF. Thanks.

**Comment by ankane** [comment]
Awesome, thanks @wschin!
